/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxyhomework;

import com.fasterxml.jackson.core.JsonProcessingException;
import proxyhomework.entity.Person;
import proxyhomework.logic.HospitalVisit;
import proxyhomework.logic.NumberWork;
import proxyhomework.psevdoSpring.AppContext;
import proxyhomework.psevdoSpring.AppRun;
import proxyhomework.service.PersonService;
import proxyhomework.service.serviceImpl.PersonServiceImpl;


public class App {
    public static void main(String[] args) {

        AppContext context = AppRun.run(App.class.getPackageName());
        HospitalVisit hospitalVisit = context.getObject(HospitalVisit.class);

        int i = 0;
        do {
            hospitalVisit.visit();
            i++;
        }while (i <11);

        PersonService<Person> personService = context.getObject(PersonServiceImpl.class);
        personService.deleteById(4);

        NumberWork numberWork = context.getObject(NumberWork.class);
        numberWork.printNumber();

    }
}
