/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxyhomework;

import proxyhomework.entity.Hospital;
import proxyhomework.entity.Person;
import proxyhomework.logic.HospitalVisit;
import proxyhomework.proxy.ProxyFactory;
import proxyhomework.service.Service;
import proxyhomework.service.serviceImpl.HospitalServiceImpl;
import proxyhomework.service.serviceImpl.PersonServiceImpl;

public class App {
    public static void main(String[] args) {
        ProxyFactory proxyFactory = new ProxyFactory(App.class.getPackage());
        Service<Person> personService =  proxyFactory.getProxy(PersonServiceImpl.class);
        Service<Hospital> hospitalService = proxyFactory.getProxy(HospitalServiceImpl.class);

        HospitalVisit hospitalVisit = new HospitalVisit(personService,hospitalService);

        int i = 0;
        do {
            hospitalVisit.visit();
            i++;
        }while (i <7);

        System.out.println("----------------");
        Person p = personService.getById(3);
        personService.deleteById(3);
        personService.save(p);
    }
}
